name: Build

on: [push, pull_request]

jobs:
  build_wheels_x86_64:
    name: Build wheels on x86_64
    runs-on: ubuntu-latest

    env:
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BEFORE_ALL: "pip3 install -r requirements.txt"
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y"
      CIBW_ARCHS_LINUX: "auto"
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_BUILD: "*-musllinux_x86_64"
      CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* cp37-*"

    steps:
      - uses: actions/checkout@v3

      - name: add additional package
        run: sudo apt-get install patchelf

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_aarch64:
    name: Build wheels on aarch64
    runs-on: ubuntu-latest

    env:
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BEFORE_ALL: "pip3 install -r requirements.txt"
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y"
      CIBW_ARCHS_LINUX: "aarch64"
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_BUILD: "*-musllinux_aarch64"
      CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* cp37-*"

    steps:
      - uses: actions/checkout@v3

      - name: add additional package
        run: sudo apt-get install patchelf

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl